[package]
name = "heimdallr"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25"
tiny-skia = "0.11"
fontdue = "0.7"

smithay-client-toolkit = "0.19"
wayland-client = "0.31"
env_logger = "0.11.8"